def menu_principal():
    print("")
    print("---------- MENÚ ----------")
    print("")
    print("1. Alta de empleado")
    print("2. Alta de auto")
    print("3. Alta de equipo")
    print("4. Simular carrera")
    print("5. Realizar consultas")
    print("6. Finalizar programa")
